site_name: LXD Tools Portal
site_url: https://siekmang.github.io/mkdocs-poc/
use_directory_urls: false

theme:
  name: material

plugins:
  - search
  - multirepo:
      # We leave this empty because the plugin is "ignoring" it anyway
      repos: []

nav:
  - Home: index.md
  - LXD Extension: "!import https://github.com/Unity-Environmental-University/lxd-tools?branch=release/3.0.0"
