site_name: LXD Tools Portal
site_url: https://siekmang.github.io/mkdocs-poc/
use_directory_urls: false

theme:
  name: material

plugins:
  - search
  - multirepo:
      # We leave this empty because the plugin is ignoring it anyway
      repos: []

nav:
  - Home: index.md
  - Learning Design Extension: "!import https://github.com/Unity-Environmental-University/lxd-tools?branch=main"
  - ueu-canvas package: "!import https://github.com/Unity-Environmental-University/ueu_canvas?branch=main"
  - Sprint Summary Script: "!import https://github.com/siekmang/trello-reporting-tool"
